repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: django-check
        name: django system check
        entry: catersync-backend/.venv/Scripts/python.exe catersync-backend/manage.py check
        language: system
        pass_filenames: false
